### ISSUE TITLE
More expressive errors

### ISSUE THREAD

**Issue by rawroland** [GillesWHC/deepl-client#17]
**Please note that this is a lower priority feature request since there are other ways to work around this**

It is currently difficult to find out the real reason a request failed since the library always returns the same error upon failure. It would be nice if the errors could correspond to the [request errors from the deepl-api](https://www.deepl.com/docs-api/accessing-the-api/error-handling/) along with the error codes.

**Comment by GillesWHC** [comment]
Allright, I'll create something that throws the error with a handy error message corresponding to the documentation you linked. Thanks for opening the issue!

**Comment by GillesWHC** [comment]
Allright, I added a basic switch that logs the error based on the status code. I published `1.0.13-beta.0`, could you check and see if it works for you? Thanks!

**Comment by GillesWHC** [comment]
After looking through the docs I added an error log which further explains the error send by the DeepL API, which I published in version `1.0.13-beta.1`.

**Comment by rawroland** [comment]
Thanks for the quick response. I have a new issue, that the request logs the error but it continues processing as if it was successful. I took a quick look at the branch `feature/error-handling` and suspect that the `hanldeError` function does not throw an error, which could explain why my try catch does not function.

**Comment by GillesWHC** [comment]
Allright, I published `1.0.13-beta.2`, in which `handleError` always throws an error.

**Comment by GillesWHC** [comment]
I published version `1.0.15` which includes the improved error handling. Don't hesitate to re-open the issue if something is wrong!

**Comment by rawroland** [comment]
@GillesWHC Sorry for the tardy response. I tested the error handling today and realised that the code still continues processing after the error is thrown. This is because the thrown error is immediately handled since the method is already wrapped in a `try` `catch` block. It would be better if users of the library handled the error, making it unnecessary for the library to handle the error or to at least propagating the error to the client.

**Comment by GillesWHC** [comment]
Allright, I'll publish version 10.0.17 which does not catch the errors. Sorry for the delay!

**Comment by rawroland** [comment]
No stress 👍🏾
